/**
 * Render captured directory badges for the product's own site. Badges are plain data (a link and an
 * image, see parseBadgeSnippet), so every format is built from those fields and never from a
 * directory's raw embed HTML.
 */
import path from "node:path";
import type { Badge, BadgeFormat } from "./schemas.js";

const BY_EXTENSION: Record<string, BadgeFormat> = {
  ".html": "html", ".htm": "html", ".json": "json", ".ts": "ts", ".tsx": "ts", ".js": "ts", ".mjs": "ts",
};

/** The explicit format, else the one the output file's extension implies, else html. */
export function badgeFormat(file: string, explicit: BadgeFormat | null): BadgeFormat {
  return explicit ?? BY_EXTENSION[path.extname(file).toLowerCase()] ?? "html";
}

const attr = (s: string) => s.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

/** `names` maps a platform slug to its display name, for formats that carry one. */
export function renderBadges(format: BadgeFormat, badges: readonly Badge[], names: Readonly<Record<string, string>> = {}): string {
  const plain = badges.map(({ platform, href, img_src, alt, width, height }) => ({ platform, href, img_src, alt, width, height }));
  if (format === "json") {
    return `${JSON.stringify(plain.map((b) => ({ ...b, name: names[b.platform] ?? b.platform })), null, 2)}\n`;
  }
  if (format === "html") {
    const links = plain.map((b) => {
      const size = `${b.width ? ` width="${b.width}"` : ""}${b.height ? ` height="${b.height}"` : ""}`;
      return `  <a href="${attr(b.href)}" target="_blank" rel="noopener"><img src="${attr(b.img_src)}" alt="${attr(b.alt || names[b.platform] || b.platform)}"${size} loading="lazy"></a>`;
    });
    return `<!-- Generated by launch-agent (npm run badges:sync); regenerated on every sync, so edit styles around it, not in it.
     Put this where the badges should appear on your site, usually the footer: paste it into your site
     builder's embed/HTML block, or include the file from your templates. Directories check that their
     link is present, so keep every link as is. -->
<div class="directory-badges" style="display:flex;flex-wrap:wrap;gap:8px;align-items:center">
${links.join("\n")}
</div>
`;
  }
  return `// Generated by launch-agent (npm run badges:sync). Do not edit by hand; edits are overwritten.
// Each entry is a directory's badge, captured from its own embed code and reduced to a link + image.

export interface DirectoryBadge {
  platform: string;
  href: string;
  img_src: string;
  alt: string;
  width: number | null;
  height: number | null;
}

export const DIRECTORY_BADGES: readonly DirectoryBadge[] = ${JSON.stringify(plain, null, 2)};
`;
}
