/**
 * The launch-watched Claude Code subagent, generated from prompts/submit.md so a watched run follows
 * exactly the headless instructions, plus what to do when the owner is watching. Its only tools are
 * the launch server's, and it starts its own copy of that server, which serves the one item
 * watch:start set up.
 *
 * In the checkout it lives at .claude/agents/launch-watched.md with paths relative to the repo; for
 * the plugin (whose subagents can't start MCP servers) `watch:agent --user` writes it to
 * ~/.claude/agents/ with absolute paths.
 */
import fs from "node:fs";
import path from "node:path";
import { ROOT } from "./paths.js";

export const WATCHED_AGENT = "launch-watched";

export const WATCHED_ADDENDUM = `## Watched run

The owner is watching this run in the launch Chrome window and can do the steps your tools can't.
When the page needs a person (a CAPTCHA or bot check that doesn't clear, an emailed code, a
password, a checkbox or button on a page the tools lock as a payment page, or anything else you
would record \`prepared_needs_human\` for), don't record. Stop calling tools and end your reply with
one line:

NEEDS_YOU: <the exact step, and on which page>

You will be resumed after the owner has done it. Start again with the \`status\` tool, look at the
page as it is now with \`snapshot\`, and carry on. Record \`prepared_needs_human\` only if the owner
says they won't do the step. Everything above still applies unchanged, including every limit on
what you may type, click or pay for.

Your final reply goes to the owner's chat: say what you did and what you recorded, in a few lines.`;

/**
 * The agent file. For the checkout, `install` is null: paths are relative to the repo and the
 * workspace is its default. For a user-level install, the absolute tool root and workspace to use.
 */
export function renderWatchedAgent(install: { root: string; workspace: string } | null): string {
  const root = install?.root ?? null;
  const at = (p: string) => (root ? path.join(root, p) : p);
  const submit = fs.readFileSync(path.join(ROOT, "prompts/submit.md"), "utf8").trim();
  return `---
name: ${WATCHED_AGENT}
description: >
  Submits one product to one directory for launch-agent while the owner watches, using only the
  guarded launch tools. Only for the launch-watched skill, after watch:start set up the item.
tools: mcp__launch
mcpServers:
  - launch:
      type: stdio
      command: ${JSON.stringify(at("node_modules/.bin/tsx"))}
      args: [${JSON.stringify(at("src/mcp/server.ts"))}]
      env:
        LA_WATCHED: "1"${install ? `\n        LAUNCH_AGENT_WORKSPACE: ${JSON.stringify(install.workspace)}` : ""}
permissionMode: dontAsk
omitClaudeMd: true
model: inherit
color: orange
---

<!-- Generated by src/watched-agent.ts from prompts/submit.md. Don't edit: run \`watch:agent\` to regenerate. -->

${submit}

${WATCHED_ADDENDUM}
`;
}

/** Where the checkout's copy lives. */
export const PROJECT_AGENT_FILE = path.join(ROOT, ".claude/agents", `${WATCHED_AGENT}.md`);
